---
- name: buildbot dependencies
  apt:
    pkg: $item
    state: present
    update_cache: yes
  with_items:
    - python
    - git
    - python-setuptools

- name: add buildbot user
  user:
    name: $buildbot_user
    home: $buildbot_home
    shell: /bin/bash
    createhome: yes

- name: "adjust GEM HOME for user"
  lineinfile:
    dest: "{{ buildbot_home }}/.bashrc"
    regexp: "^export GEM_HOME"
    line: "export GEM_HOME=$HOME/.gem"
    insertbefore: BOF
    state: present

- name: "add gem paths to path"
  lineinfile:
    dest: "{{ buildbot_home }}/.bashrc"
    regexp: "^export PATH=.GEM_HOME"
    line: "export PATH=$GEM_HOME/bin:$PATH"
    insertafter: "GEM_HOME"
    state: present

- name: install buildbot
  easy_install:
    name: $item
  with_items:
    - buildbot
    - buildbot-slave

- name: create buildbot master directory
  sudo_user: $buildbot_user
  file:
    path: "{{ buildbot_home }}/master"
    state: directory

- name: create buildbot slave directories
  sudo_user: $buildbot_user
  file:
    path: "{{ buildbot_home }}/slaves/{{ item.name }}"
    state: directory
  with_items: $buildbot_slaves

# master configuration
- name: create buildbot master
  sudo_user: $buildbot_user
  shell: chdir={{ buildbot_home }} buildbot create-master master

- name: buildbot master configuration
  sudo_user: $buildbot_user
  template:
    src: master.cfg.js
    dest: "{{ buildbot_home }}/master/master.cfg"

- name: buildbot slave configuration
  sudo_user: $buildbot_user
  shell: chdir={{ buildbot_home }}/slaves/{{ item.name }} buildslave create-slave . {{ buildbot_web_host }}:{{ buildbot_slave_port }} {{ item.name }} {{ item.password }}
  with_items: $buildbot_slaves

# buildbot start --nodaemon master

#   - buildslave create-slave /tmp/experimental_buildslave localhost:9989 example-slave pass
#   - buildslave start /tmp/experimental_buildslave

#   # changing master config
#   - cd /tmp/experimental_buildmaster && buildbot reconfig master
#   # basic login: pyflakes//pyflakes